alertmanager:
  enabled: false

grafana:
  imageRenderer:
    grafanaProtocol: https
  
  grafana.ini:
    server:
      domain: dashboard.bacchus.io
      root_url: "https://%(domain)s"
    auth.github:
      enabled: true
      allow_sign_up: true
      scopes: user:email,read:org
      auth_url: https://github.com/login/oauth/authorize
      token_url: https://github.com/login/oauth/access_token
      api_url: https://api.github.com/user
      allowed_organizations: bacchus-snu
      client_id: '1d692134938f08d650f4'
      client_secret: '$__file{/etc/secrets/github-oauth/secret}'
  
  extraSecretMounts:
  - name: github-oauth-mount
    secretName: github-oauth
    defaultMode: 0440
    mountPath: /etc/secrets/github-oauth
    readOnly: true

  persistence:
    enabled: true
    type: pvc
    size: 20Gi

  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/scheme: internet-facing
    hosts:
    - dashboard.bacchus.io
